#!/bin/bash

# this tool is licensed under the gpl 3.0 >:( (fear me lmao)

# VARIABLES

pathtoconfig="/etc/ffetchconfig" # by default it is at /etc/ffetchconfig
futurefetchver="0.2.0" # version of this tool
accentcolor=$(head -n 20 "$pathtoconfig" | tail -1)
secondcolor=$(head -n 24 "$pathtoconfig" | tail -1)
showcredits=$(head -n 41 "$pathtoconfig" | tail -1)

# PRINT STUFF

print_logo(){
  linen=28
  endlinen=37
  until [ $linen -gt "$endlinen" ]
  do
    linecont=$(head -n +"$linen" "$pathtoconfig" | tail -n 1)
    echo -e "$linecont"
    linen=$((linen + 1))
  done
}

print_universal_info(){
  echo -e "$accentcolor OS Name$secondcolor $(cat /etc/os-release | grep -oP '(?<=^NAME=).+' | tr -d '"')"
  echo -e "$accentcolor OS Name 2$secondcolor $(uname -o)"
  echo -e "$accentcolor OS Version$secondcolor $(cat /etc/os-release | grep -oP '(?<=^VERSION=).+' | tr -d '"')"
  echo -e "$accentcolor OS Homepage$secondcolor $(cat /etc/os-release | grep -oP '(?<=^HOME_URL=).+' | tr -d '"')"
  echo -e "$accentcolor OS Kernel$secondcolor $(uname -s -r)"
  echo -e "$accentcolor Architecture$secondcolor $(uname -m)"
  echo -e "$accentcolor DE + Session$secondcolor $XDG_CURRENT_DESKTOP + $DESKTOP_SESSION"
  echo -e "$accentcolor CPU$secondcolor $(lscpu | awk -F': *' '/Model name/{print $2}')"
  echo -e "$accentcolor GPU$secondcolor $(lshw 2>/dev/null -C display | grep product | head -n 1 | awk '{print $2, $3}')"
  echo -e "$accentcolor Memory$secondcolor $(awk '/MemTotal/{print $2/1024}' /proc/meminfo) MB"
  echo -e "$accentcolor Future Fetch Version$secondcolor $futurefetchver"
}

print_credits(){
  echo -e "\033[1;92mfuturefetch \033[0mby \033[46mitsnotaz\033[0m \033[4;37m(https://itsnotaz.github.io/website/)"
}

#print_special(){
#}                  #COMING SOON :D

# RUN STUFF

echo ""
print_logo
echo ""
print_universal_info
if [[ "$showcredits" == "YES" ]]; then
  echo ""
  print_credits
  exit 0
elif [[ "$showcredits" == "NO" ]]; then
  exit 0
else
  echo -e "\033[0;32mERROR (futurefetch): $showcredits is an invalid option for SHOW CREDITS in $pathtoconfig"
  exit 1
fi
#echo ""
#print_special
